#import <Foundation/Foundation.h>
#import "OAIUser.h"
#import "OAIApi.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIAdminApi: NSObject <OAIApi>

extern NSString* kOAIAdminApiErrorDomain;
extern NSInteger kOAIAdminApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Get user by admin credentials.
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param authorization  (optional)
/// @param authUser  (optional)
/// @param cacheControl  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `Cache-Control` or `AuthUser` or `Authorization`",
///  code:404 message:"`uuid` not found"
///
/// @return OAIUser*
-(NSURLSessionTask*) adminUuidGetWithUuid: (NSString*) uuid
    authorization: (NSString*) authorization
    authUser: (NSString*) authUser
    cacheControl: (NSString*) cacheControl
    completionHandler: (void (^)(OAIUser* output, NSError* error)) handler;



@end
