#import <Foundation/Foundation.h>
#import "OAIForgotPasswordData.h"
#import "OAIInlineResponse400.h"
#import "OAIInlineResponse415.h"
#import "OAIUpdatePasswordData.h"
#import "OAIApi.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIAccountApi: NSObject <OAIApi>

extern NSString* kOAIAccountApiErrorDomain;
extern NSInteger kOAIAccountApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Validate password reset token
/// The second step in the forgotten password reset procedure is to ensure that the password reset token is still valid. Each token can be used at most once and it is valid for a limited duration.
///
/// @param body 
/// 
///  code:204 message:"",
///  code:400 message:"Invalid `body`",
///  code:415 message:"Unsupported media type"
///
/// @return void
-(NSURLSessionTask*) accountPasswordCheckTokenPostWithBody: (NSString*) body
    completionHandler: (void (^)(NSError* error)) handler;


/// Request password reset link
/// This is the starting point of the forgotten password recovery process. It sends a password reset link with a pasword reset token to the given user's email address if such user and email address exist.
///
/// @param body 
/// 
///  code:204 message:"",
///  code:400 message:"Invalid `body`",
///  code:415 message:"Unsupported media type"
///
/// @return void
-(NSURLSessionTask*) accountPasswordForgotPostWithBody: (OAIForgotPasswordData*) body
    completionHandler: (void (^)(NSError* error)) handler;


/// Reset a forgotten password with a token
/// The final step of the forgotten password reset procedure performs password reset with a token obtained from the email message sent by the POST /password/forgot endpoint and the new password and its confirmation.
///
/// @param body 
/// 
///  code:204 message:"",
///  code:400 message:"Invalid `body`",
///  code:415 message:"Unsupported media type"
///
/// @return void
-(NSURLSessionTask*) accountPasswordResetPostWithBody: (OAIUpdatePasswordData*) body
    completionHandler: (void (^)(NSError* error)) handler;



@end
