#import <Foundation/Foundation.h>
#import "OAIForgotPasswordData.h"
#import "OAIInlineResponse400.h"
#import "OAIInlineResponse415.h"
#import "OAIUpdatePasswordData.h"
#import "OAIApi.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIAccountApi: NSObject <OAIApi>

extern NSString* kOAIAccountApiErrorDomain;
extern NSInteger kOAIAccountApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Request password reset link
/// 
///
/// @param body 
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body`",
///  code:415 message:"Unsupported media type"
///
/// @return NSArray<NSObject*>*
-(NSURLSessionTask*) accountPasswordForgotPostWithBody: (OAIForgotPasswordData*) body
    completionHandler: (void (^)(NSArray<NSObject*>* output, NSError* error)) handler;


/// Reset a forgotten password with a token
/// 
///
/// @param body 
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body`",
///  code:415 message:"Unsupported media type"
///
/// @return NSArray<NSObject*>*
-(NSURLSessionTask*) accountPasswordResetPostWithBody: (OAIUpdatePasswordData*) body
    completionHandler: (void (^)(NSArray<NSObject*>* output, NSError* error)) handler;



@end
