#import <Foundation/Foundation.h>
#import "OAICancelSubscriptionReason.h"
#import "OAIDeleteTempAddressChangeDates.h"
#import "OAIDeliveryReclamation.h"
#import "OAIGdprConsent.h"
#import "OAIInlineResponse400.h"
#import "OAIInlineResponse415.h"
#import "OAILegalConsent.h"
#import "OAILoginResponse.h"
#import "OAINewDeliveryReclamation.h"
#import "OAINewTemporaryUser.h"
#import "OAINewUser.h"
#import "OAINewsletterSubscriptions.h"
#import "OAISubscription.h"
#import "OAISubscriptionPauseDates.h"
#import "OAISubscriptionPauseEdit.h"
#import "OAISubscriptionPayments.h"
#import "OAITemporaryAddressChange.h"
#import "OAITemporaryAddressChangeDates.h"
#import "OAIUser.h"
#import "OAIUserUpdate.h"
#import "OAIUserUpdatePassword.h"
#import "OAIApi.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIUsersApi: NSObject <OAIApi>

extern NSString* kOAIUsersApiErrorDomain;
extern NSInteger kOAIUsersApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Create a new user.
/// 
///
/// @param body 
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body`",
///  code:415 message:"Unsupported media type"
///
/// @return OAILoginResponse*
-(NSURLSessionTask*) usersPostWithBody: (OAINewUser*) body
    completionHandler: (void (^)(OAILoginResponse* output, NSError* error)) handler;


/// Create a new user with email.
/// 
///
/// @param body 
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body`",
///  code:415 message:"Unsupported media type"
///
/// @return OAILoginResponse*
-(NSURLSessionTask*) usersTemporaryPostWithBody: (OAINewTemporaryUser*) body
    completionHandler: (void (^)(OAILoginResponse* output, NSError* error)) handler;


/// Get users entitlements.
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// @param cacheControl  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `Cache-Control` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found"
///
/// @return NSArray<NSString*>*
-(NSURLSessionTask*) usersUuidEntitlementGetWithUuid: (NSString*) uuid
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    cacheControl: (NSString*) cacheControl
    completionHandler: (void (^)(NSArray<NSString*>* output, NSError* error)) handler;


/// Updates the GDPR consent settings for a given user.
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAIUser*
-(NSURLSessionTask*) usersUuidGdprPutWithUuid: (NSString*) uuid
    body: (NSArray<OAIGdprConsent>*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAIUser* output, NSError* error)) handler;


/// Get user by UUID.
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// @param cacheControl  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `Cache-Control` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found"
///
/// @return OAIUser*
-(NSURLSessionTask*) usersUuidGetWithUuid: (NSString*) uuid
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    cacheControl: (NSString*) cacheControl
    completionHandler: (void (^)(OAIUser* output, NSError* error)) handler;


/// Updates the legal consent settings for a given user.
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAIUser*
-(NSURLSessionTask*) usersUuidLegalPutWithUuid: (NSString*) uuid
    body: (NSArray<OAILegalConsent>*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAIUser* output, NSError* error)) handler;


/// Get newsletter subscriptions
/// Get list of newsletter subscriptions from mailchimp
///
/// @param uuid 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found"
///
/// @return OAINewsletterSubscriptions*
-(NSURLSessionTask*) usersUuidNewslettersGetWithUuid: (NSString*) uuid
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAINewsletterSubscriptions* output, NSError* error)) handler;


/// Update newsletter subscriptions
/// Get list of newsletter subscriptions from mailchimp
///
/// @param uuid 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAINewsletterSubscriptions*
-(NSURLSessionTask*) usersUuidNewslettersPutWithUuid: (NSString*) uuid
    body: (OAINewsletterSubscriptions*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAINewsletterSubscriptions* output, NSError* error)) handler;


/// Set / Change user password
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAIUser*
-(NSURLSessionTask*) usersUuidPasswordPutWithUuid: (NSString*) uuid
    body: (OAIUserUpdatePassword*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAIUser* output, NSError* error)) handler;


/// Update a user
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAIUser*
-(NSURLSessionTask*) usersUuidPatchWithUuid: (NSString*) uuid
    body: (OAIUserUpdate*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAIUser* output, NSError* error)) handler;


/// Get user's subscriptions and payment events
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` not found"
///
/// @return NSArray<OAISubscriptionPayments>*
-(NSURLSessionTask*) usersUuidPaymentsGetWithUuid: (NSString*) uuid
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(NSArray<OAISubscriptionPayments>* output, NSError* error)) handler;


/// Check if user has valid token for a scope
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param authorization  (optional)
/// @param scope  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `scope` or `Authorization`",
///  code:404 message:"`uuid` not found"
///
/// @return NSNumber*
-(NSURLSessionTask*) usersUuidScopeGetWithUuid: (NSString*) uuid
    authorization: (NSString*) authorization
    scope: (NSString*) scope
    completionHandler: (void (^)(NSNumber* output, NSError* error)) handler;


/// Delete temporary address change for subscription
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAISubscription*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoAddressChangeDeleteWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    body: (OAIDeleteTempAddressChangeDates*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAISubscription* output, NSError* error)) handler;


/// Edit temporary address change dates of a subscription
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAISubscription*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoAddressChangePatchWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    body: (OAITemporaryAddressChangeDates*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAISubscription* output, NSError* error)) handler;


/// Make a temporary address change for a subscription
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAISubscription*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoAddressChangePostWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    body: (OAITemporaryAddressChange*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAISubscription* output, NSError* error)) handler;


/// Cancels user subscription
/// The subscription continues to be valid until the end of the billing period. Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAISubscription*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoCancelPutWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    body: (OAICancelSubscriptionReason*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAISubscription* output, NSError* error)) handler;


/// Edit pause duration
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAISubscription*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoPausePatchWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    body: (OAISubscriptionPauseEdit*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAISubscription* output, NSError* error)) handler;


/// Pause users subscription
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAISubscription*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoPausePostWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    body: (OAISubscriptionPauseDates*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAISubscription* output, NSError* error)) handler;


/// Create a new delivery reclamation for a subscription
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param body 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `body` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` not found",
///  code:415 message:"Unsupported media type"
///
/// @return OAIDeliveryReclamation*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoReclamationPostWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    body: (OAINewDeliveryReclamation*) body
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAIDeliveryReclamation* output, NSError* error)) handler;


/// Get a delivery reclamation
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param reclaimno 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` or `reclaimno` not found"
///
/// @return OAIDeliveryReclamation*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoReclamationsReclaimnoGetWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    reclaimno: (NSNumber*) reclaimno
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    completionHandler: (void (^)(OAIDeliveryReclamation* output, NSError* error)) handler;


/// Unpause users subscription
/// Authorization header expects the following format ‘OAuth {token}’
///
/// @param uuid 
/// @param subsno 
/// @param authUser  (optional)
/// @param authorization  (optional)
/// @param startDate  (optional)
/// @param endDate  (optional)
/// 
///  code:200 message:"",
///  code:400 message:"Invalid `endDate` or `startDate` or `Authorization` or `AuthUser`",
///  code:404 message:"`uuid` or `subsno` not found"
///
/// @return OAISubscription*
-(NSURLSessionTask*) usersUuidSubscriptionsSubsnoUnpausePostWithUuid: (NSString*) uuid
    subsno: (NSNumber*) subsno
    authUser: (NSString*) authUser
    authorization: (NSString*) authorization
    startDate: (NSDate*) startDate
    endDate: (NSDate*) endDate
    completionHandler: (void (^)(OAISubscription* output, NSError* error)) handler;



@end
