#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIActiveDays
@end

@interface OAIActiveDays : OAIObject

/* Active on Monday 
 */
@property(nonatomic) NSNumber* mon;
/* Active on Tuesday 
 */
@property(nonatomic) NSNumber* tue;
/* Active on Wednedsday 
 */
@property(nonatomic) NSNumber* wed;
/* Active on Thursday 
 */
@property(nonatomic) NSNumber* thu;
/* Active on Friday 
 */
@property(nonatomic) NSNumber* fri;
/* Active on Saturday 
 */
@property(nonatomic) NSNumber* sat;
/* Active on Sunday 
 */
@property(nonatomic) NSNumber* sun;

@end
