#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIActiveDays
@end

@interface OAIActiveDays : OAIObject


@property(nonatomic) NSNumber* mon;

@property(nonatomic) NSNumber* tue;

@property(nonatomic) NSNumber* wed;

@property(nonatomic) NSNumber* thu;

@property(nonatomic) NSNumber* fri;

@property(nonatomic) NSNumber* sat;

@property(nonatomic) NSNumber* sun;

@end
