#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIDeliveryReclamation
@end

@interface OAIDeliveryReclamation : OAIObject


@property(nonatomic) NSNumber* number;

@property(nonatomic) NSNumber* customerNumber;

@property(nonatomic) NSNumber* subscriptionNumber;

@property(nonatomic) NSDate* date;

@property(nonatomic) NSDate* publicationDate;

@property(nonatomic) NSString* claim;

@property(nonatomic) NSString* status;

@end
