#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIDeliveryAddress
@end

@interface OAIDeliveryAddress : OAIObject

/* Street address, containing all details [optional]
 */
@property(nonatomic) NSString* streetAddress;
/*  
 */
@property(nonatomic) NSString* zipcode;
/*  [optional]
 */
@property(nonatomic) NSString* city;
/* Temporary name (or c/o) of delivery address [optional]
 */
@property(nonatomic) NSString* temporaryName;

@end
