#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIDescriptionFrequency
@end

@interface OAIDescriptionFrequency : OAIObject


@property(nonatomic) NSNumber* amount;

@property(nonatomic) NSString* unit;

@end
