#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIGdprConsent
@end

@interface OAIGdprConsent : OAIObject


@property(nonatomic) NSString* brand;

@property(nonatomic) NSString* consentKey;

@property(nonatomic) NSNumber* value;

@end
