#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse403InvalidCredentials.h"
@protocol OAIInlineResponse403InvalidCredentials;
@class OAIInlineResponse403InvalidCredentials;



@protocol OAIInlineResponse403
@end

@interface OAIInlineResponse403 : OAIObject


@property(nonatomic) NSNumber* httpCode;

@property(nonatomic) NSString* httpStatus;

@property(nonatomic) OAIInlineResponse403InvalidCredentials* invalidCredentials;

@end
