#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInlineResponse4032EmailAddressInUse
@end

@interface OAIInlineResponse4032EmailAddressInUse : OAIObject


@property(nonatomic) NSString* mergeToken;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* existingProvider;

@end
