#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse4032EmailAddressInUse.h"
#import "OAIInlineResponse4032EmailNotAuthorized.h"
#import "OAIInlineResponse4032OauthFailed.h"
@protocol OAIInlineResponse4032EmailAddressInUse;
@class OAIInlineResponse4032EmailAddressInUse;
@protocol OAIInlineResponse4032EmailNotAuthorized;
@class OAIInlineResponse4032EmailNotAuthorized;
@protocol OAIInlineResponse4032OauthFailed;
@class OAIInlineResponse4032OauthFailed;



@protocol OAIInlineResponse4032
@end

@interface OAIInlineResponse4032 : OAIObject


@property(nonatomic) OAIInlineResponse4032EmailAddressInUse* emailAddressInUse;

@property(nonatomic) NSNumber* httpCode;

@property(nonatomic) OAIInlineResponse4032OauthFailed* oauthFailed;

@property(nonatomic) NSString* httpStatus;

@property(nonatomic) OAIInlineResponse4032EmailNotAuthorized* emailNotAuthorized;

@end
