#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIInlineResponse400InvalidRequestBody.h"
@protocol OAIInlineResponse400InvalidRequestBody;
@class OAIInlineResponse400InvalidRequestBody;



@protocol OAIInlineResponse400
@end

@interface OAIInlineResponse400 : OAIObject


@property(nonatomic) NSNumber* httpCode;

@property(nonatomic) OAIInlineResponse400InvalidRequestBody* invalidRequestBody;

@property(nonatomic) NSString* httpStatus;

@end
