#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAILoginResponse
@end

@interface OAILoginResponse : OAIObject


@property(nonatomic) NSString* token;

@property(nonatomic) NSString* ssoCode;

@property(nonatomic) NSString* uuid;

@property(nonatomic) NSNumber* isAdmin;

@end
