#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAILoginDataSSO
@end

@interface OAILoginDataSSO : OAIObject


@property(nonatomic) NSString* uuid;

@property(nonatomic) NSString* accessToken;

@end
