#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIClaimType.h"
@protocol OAIClaimType;
@class OAIClaimType;



@protocol OAINewDeliveryReclamation
@end

@interface OAINewDeliveryReclamation : OAIObject


@property(nonatomic) NSDate* publicationDate;

@property(nonatomic) OAIClaimType* claim;

@end
