#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAINewsletterSubscription.h"
@protocol OAINewsletterSubscription;
@class OAINewsletterSubscription;



@protocol OAINewsletter
@end

@interface OAINewsletter : OAIObject


@property(nonatomic) NSString* listId;

@property(nonatomic) NSString* paper;

@property(nonatomic) NSDictionary<NSString*, NSArray<OAINewsletterSubscription>*>* subscriptions;

@end
