#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAINewUser
@end

@interface OAINewUser : OAIObject


@property(nonatomic) NSString* varNewUserFirstName;

@property(nonatomic) NSString* varNewUserLastName;

@property(nonatomic) NSString* varNewUserEmailAddress;

@property(nonatomic) NSString* varNewUserPassword;

@property(nonatomic) NSString* varNewUserConfirmPassword;

@property(nonatomic) NSString* varNewUserStreetAddress;

@property(nonatomic) NSString* varNewUserZipCode;

@property(nonatomic) NSString* varNewUserCity;

@property(nonatomic) NSString* varNewUserCountry;

@property(nonatomic) NSString* varNewUserPhone;

@end
