#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAINewsletterSubscriptions
@end

@interface OAINewsletterSubscriptions : OAIObject


@property(nonatomic) NSNumber* norden;

@property(nonatomic) NSNumber* daily;

@property(nonatomic) NSNumber* kultur;

@end
