#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPausedSubscription
@end

@interface OAIPausedSubscription : OAIObject


@property(nonatomic) NSNumber* subsno;

@property(nonatomic) NSDate* sleepStartdate;

@property(nonatomic) NSDate* sleepEndDate;

@property(nonatomic) NSString* creditType;

@property(nonatomic) NSNumber* creditAmount;

@property(nonatomic) NSString* sleepType;

@property(nonatomic) NSNumber* credited;

@property(nonatomic) NSNumber* creditInvno;

@property(nonatomic) NSString* bookingDate;

@property(nonatomic) NSNumber* allowWebpaper;

@property(nonatomic) NSString* receiveType;

@property(nonatomic) NSString* confirmStatus;

@property(nonatomic) NSString* stampUser;

@end
