#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIDescriptionFrequency.h"
@protocol OAIDescriptionFrequency;
@class OAIDescriptionFrequency;



@protocol OAIPackageDescription
@end

@interface OAIPackageDescription : OAIObject

/* Brand name 
 */
@property(nonatomic) NSString* brand;
/* Brand name, long 
 */
@property(nonatomic) NSString* brandLong;
/* Short description 
 */
@property(nonatomic) NSString* descShort;
/* Long description 
 */
@property(nonatomic) NSString* descLong;
/* Url for the current package 
 */
@property(nonatomic) NSString* url;
/* How many days the package is active 
 */
@property(nonatomic) NSString* days;
/* Weekdays for which the package is active 
 */
@property(nonatomic) NSString* weekdays;

@property(nonatomic) OAIDescriptionFrequency* frequency;
/* Entitlements included in the package 
 */
@property(nonatomic) NSArray<NSString*>* includes;

@end
