#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIDescriptionFrequency.h"
@protocol OAIDescriptionFrequency;
@class OAIDescriptionFrequency;



@protocol OAIPackageDescription
@end

@interface OAIPackageDescription : OAIObject


@property(nonatomic) NSString* brand;

@property(nonatomic) NSString* brandLong;

@property(nonatomic) NSString* descShort;

@property(nonatomic) NSString* descLong;

@property(nonatomic) NSString* url;

@property(nonatomic) NSString* days;

@property(nonatomic) NSString* weekdays;

@property(nonatomic) OAIDescriptionFrequency* frequency;

@property(nonatomic) NSArray<NSString*>* includes;

@end
