#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPackageOffer
@end

@interface OAIPackageOffer : OAIObject

/* Duration of the offer 
 */
@property(nonatomic) NSNumber* months;
/* Amount of cents that has to be paid 
 */
@property(nonatomic) NSNumber* totalPrice;
/* Amount of cents that has to be paid 
 */
@property(nonatomic) NSNumber* monthlyPrice;

@end
