#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPayment
@end

@interface OAIPayment : OAIObject


@property(nonatomic) NSNumber* invno;

@property(nonatomic) NSDate* date;

@property(nonatomic) NSDate* dueDate;

@property(nonatomic) NSNumber* expenses;

@property(nonatomic) NSNumber* interest;

@property(nonatomic) NSNumber* vat;

@property(nonatomic) NSNumber* amount;

@property(nonatomic) NSNumber* openAmount;

@property(nonatomic) NSString* type;

@property(nonatomic) NSString* state;

@property(nonatomic) NSNumber* discPercent;

@property(nonatomic) NSNumber* discAmount;

@property(nonatomic) NSString* reference;

@end
