#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPastTemporaryAddress
@end

@interface OAIPastTemporaryAddress : OAIObject

/* Country code 
 */
@property(nonatomic) NSString* countryCode;
/* Zip code 
 */
@property(nonatomic) NSString* zipcode;
/* City [optional]
 */
@property(nonatomic) NSString* cityName;
/* Street 
 */
@property(nonatomic) NSString* street;
/* Temporary name (c/o) [optional]
 */
@property(nonatomic) NSString* temporaryName;

@end
