#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPausedSubscription
@end

@interface OAIPausedSubscription : OAIObject


@property(nonatomic) NSNumber* pausedSubscriptionSubsno;

@property(nonatomic) NSDate* pausedSubscriptionSleepStartDate;

@property(nonatomic) NSDate* pausedSubscriptionSleepEndDate;

@property(nonatomic) NSString* pausedSubscriptionCreditType;

@property(nonatomic) NSNumber* pausedSubscriptionCreditAmount;

@property(nonatomic) NSString* pausedSubscriptionSleepType;

@property(nonatomic) NSNumber* pausedSubscriptionCredited;

@property(nonatomic) NSNumber* pausedSubscriptionCreditInvno;

@property(nonatomic) NSString* pausedSubscriptionBookingDate;

@property(nonatomic) NSNumber* pausedSubscriptionAllowWebpaper;

@property(nonatomic) NSString* pausedSubscriptionReceiveType;

@property(nonatomic) NSString* pausedSubscriptionConfirmStatus;

@property(nonatomic) NSString* pausedSubscriptionStampUser;

@end
