#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* OpenAPI spec version: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPackageOffer
@end

@interface OAIPackageOffer : OAIObject


@property(nonatomic) NSNumber* months;

@property(nonatomic) NSNumber* totalPrice;

@property(nonatomic) NSNumber* monthlyPrice;

@end
