#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIPackageCampaign
@end

@interface OAIPackageCampaign : OAIObject

/* Campaign number 
 */
@property(nonatomic) NSNumber* no;
/* Campaign id 
 */
@property(nonatomic) NSString* _id;
/* Campaign name 
 */
@property(nonatomic) NSString* name;
/* Price of campaign in euros 
 */
@property(nonatomic) NSNumber* priceEur;
/* Length of campaign 
 */
@property(nonatomic) NSNumber* length;
/* Unit of length (days, weeks, months, years) 
 */
@property(nonatomic) NSString* lengthUnit;

@end
