#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIPayment.h"
@protocol OAIPayment;
@class OAIPayment;



@protocol OAISubscriptionPayments
@end

@interface OAISubscriptionPayments : OAIObject

/* Product subsno 
 */
@property(nonatomic) NSNumber* subsno;
/* Package name 
 */
@property(nonatomic) NSString* name;

@property(nonatomic) NSDate* startDate;

@property(nonatomic) NSDate* lastDate;
/* Payments 
 */
@property(nonatomic) NSArray<OAIPayment>* payments;

@end
