#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAISubscriptionDates
@end

@interface OAISubscriptionDates : OAIObject

/* Length of Subscription in months [optional]
 */
@property(nonatomic) NSNumber* lenMonths;
/* Additional days (on top of months) for Subscription duration [optional]
 */
@property(nonatomic) NSNumber* lenDays;

@property(nonatomic) NSDate* start;

@property(nonatomic) NSDate* end;

@property(nonatomic) NSDate* unpaidBreak;

@property(nonatomic) NSDate* invoicingStart;

@property(nonatomic) NSDate* paidUntil;

@property(nonatomic) NSDate* suspend;

@end
