#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIFaroUser.h"
#import "OAIJanrainUser.h"
@protocol OAIFaroUser;
@class OAIFaroUser;
@protocol OAIJanrainUser;
@class OAIJanrainUser;



@protocol OAISearchResult
@end

@interface OAISearchResult : OAIObject


@property(nonatomic) OAIJanrainUser* janrain;

@property(nonatomic) NSArray<OAIFaroUser>* faro;

@end
