#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIUserUpdateAddress.h"
@protocol OAIUserUpdateAddress;
@class OAIUserUpdateAddress;



@protocol OAIUserUpdate
@end

@interface OAIUserUpdate : OAIObject


@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) OAIUserUpdateAddress* address;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* phone;

@property(nonatomic) NSArray<NSObject*>* pendingAddressChanges;

@property(nonatomic) NSNumber* updateCusno;

@end
