#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Persona
* KSF Media unified login service
*
* The version of the OpenAPI document: 1.3.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIAddress.h"
#import "OAIGdprConsent.h"
#import "OAILegalConsent.h"
#import "OAISubscription.h"
@protocol OAIAddress;
@class OAIAddress;
@protocol OAIGdprConsent;
@class OAIGdprConsent;
@protocol OAILegalConsent;
@class OAILegalConsent;
@protocol OAISubscription;
@class OAISubscription;



@protocol OAIUser
@end

@interface OAIUser : OAIObject


@property(nonatomic) NSString* uuid;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) OAIAddress* address;

@property(nonatomic) NSString* cusno;

@property(nonatomic) NSArray<OAISubscription>* subs;

@property(nonatomic) NSArray<OAIGdprConsent>* consent;

@property(nonatomic) NSArray<OAILegalConsent>* legal;

@end
